"""Drift guard for the two discovery-shim pairs, each with two locations.

Hermes has two separate plugin subsystems that both apply to this package
(verified against ``hermes_cli/plugins.py`` in a real Hermes checkout):

  * **Model-provider discovery** (``providers._discover_providers``) scans
    ``plugins/model-providers/<name>/``, imports ``__init__.py``, and expects
    it to call ``register_provider(profile)`` as an import-time side effect.
    Always-on, no opt-in. Its manifest's ``kind: model-provider`` is what
    tells Hermes' *general* plugin scanner (which also sees this directory
    while walking ``plugins/``) to skip it rather than double-load it.
  * **General-plugin discovery** (``hermes_cli.plugins.PluginManager``) scans
    ``plugins/<name>/`` (flat), imports ``__init__.py``, and calls
    ``module.register(ctx)`` *itself* — the shim must only expose
    ``register``, never call it. Its manifest's ``kind: standalone`` makes
    Hermes gate it behind ``hermes plugins enable hermes-claude-code``.

Each subsystem's discovery directory exists in two places: checked into this
repo (for "vendor-drop this repo directly into a hermes-agent checkout's own
plugins dir") and generated by ``install.py`` into ``$HERMES_HOME`` (for the
documented "pip install, then run the installer" flow). Hermes' model-provider
discovery never parses ``plugin.yaml`` at runtime (only ``__init__.py``
matters there), and the general PluginManager only reads it for a handful of
fields — nothing round-trips it back to a single source of truth, so these
tests are what stops the checked-in and generated copies from drifting apart.
"""

from __future__ import annotations

from pathlib import Path

from hermes_claude_code import __version__, install
from hermes_claude_code.config import DESCRIPTION, PROVIDER_NAME

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PROVIDER_CHECKED_IN = _REPO_ROOT / "plugins" / "model-providers" / "hermes-claude-code"
_GENERAL_CHECKED_IN = _REPO_ROOT / "plugins" / "hermes-claude-code"


def _parse_yaml_fields(text: str) -> dict[str, str]:
    """Minimal ``key: value`` reader — good enough for our flat manifest."""
    fields: dict[str, str] = {}
    for line in text.splitlines():
        if ":" not in line or line.startswith(" "):
            continue
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip().strip('"')
    return fields


# -- model-provider shim ----------------------------------------------------- #
def test_provider_manifest_matches_config():
    fields = _parse_yaml_fields(
        (_PROVIDER_CHECKED_IN / "plugin.yaml").read_text(encoding="utf-8")
    )
    assert fields["name"] == PROVIDER_NAME
    assert fields["kind"] == "model-provider"
    assert fields["version"] == __version__
    assert fields["description"] == DESCRIPTION


def test_provider_manifest_checked_in_matches_installed(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    install.install()
    dest = tmp_path / "plugins" / "model-providers" / PROVIDER_NAME

    checked_in = _parse_yaml_fields(
        (_PROVIDER_CHECKED_IN / "plugin.yaml").read_text(encoding="utf-8")
    )
    generated = _parse_yaml_fields((dest / "plugin.yaml").read_text(encoding="utf-8"))
    for key in ("name", "kind", "version", "description"):
        assert generated[key] == checked_in[key], f"plugin.yaml field '{key}' drifted"


def test_provider_init_self_invokes_register(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    install.install()
    dest = tmp_path / "plugins" / "model-providers" / PROVIDER_NAME

    checked_in_init = (_PROVIDER_CHECKED_IN / "__init__.py").read_text(encoding="utf-8")
    generated_init = (dest / "__init__.py").read_text(encoding="utf-8")
    for text in (checked_in_init, generated_init):
        assert "from hermes_claude_code.plugin import register" in text
        # providers._discover_providers never calls anything — the shim must.
        assert "register()" in text


# -- general plugin shim ------------------------------------------------------ #
def test_general_manifest_matches_config():
    fields = _parse_yaml_fields(
        (_GENERAL_CHECKED_IN / "plugin.yaml").read_text(encoding="utf-8")
    )
    assert fields["name"] == PROVIDER_NAME
    assert fields["kind"] == "standalone"
    assert fields["version"] == __version__
    assert fields["description"] == DESCRIPTION


def test_general_manifest_declares_the_session_start_hook():
    text = (_GENERAL_CHECKED_IN / "plugin.yaml").read_text(encoding="utf-8")
    assert "provides_hooks" in text
    assert "on_session_start" in text


def test_general_manifest_checked_in_matches_installed(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    install.install()
    dest = tmp_path / "plugins" / PROVIDER_NAME

    checked_in = _parse_yaml_fields(
        (_GENERAL_CHECKED_IN / "plugin.yaml").read_text(encoding="utf-8")
    )
    generated = _parse_yaml_fields((dest / "plugin.yaml").read_text(encoding="utf-8"))
    for key in ("name", "kind", "version", "description"):
        assert generated[key] == checked_in[key], f"plugin.yaml field '{key}' drifted"


def test_general_init_does_not_self_invoke_register(tmp_path, monkeypatch):
    monkeypatch.setenv("HERMES_HOME", str(tmp_path))
    install.install()
    dest = tmp_path / "plugins" / PROVIDER_NAME

    checked_in_init = (_GENERAL_CHECKED_IN / "__init__.py").read_text(encoding="utf-8")
    generated_init = (dest / "__init__.py").read_text(encoding="utf-8")
    for text in (checked_in_init, generated_init):
        assert "from hermes_claude_code.plugin import register" in text
        # PluginManager calls register(ctx) itself; self-invoking here would
        # run registration twice.
        assert "register()" not in text
