from __future__ import annotations

import os

import pytest

from hermes_claude_code import install as installer
from hermes_claude_code.config import PROVIDER_NAME


def test_install_writes_both_owned_discovery_dirs(tmp_path):
    result = installer.install(tmp_path)
    provider = tmp_path / "plugins" / "model-providers" / PROVIDER_NAME
    general = tmp_path / "plugins" / PROVIDER_NAME
    assert result["status"] == "installed"
    assert result["general_plugin_enabled"] is False
    for directory in (provider, general):
        init_file = directory / "__init__.py"
        manifest = directory / "plugin.yaml"
        assert init_file.read_text().startswith("# Generated by")
        assert manifest.exists()
        if os.name != "nt":
            assert directory.stat().st_mode & 0o777 == 0o700
            assert init_file.stat().st_mode & 0o777 == 0o600
            assert manifest.stat().st_mode & 0o777 == 0o600


def test_install_is_idempotent_after_python_cache_creation(tmp_path):
    installer.install(tmp_path)
    cache = tmp_path / "plugins" / PROVIDER_NAME / "__pycache__"
    cache.mkdir()
    (cache / "__init__.cpython-311.pyc").write_bytes(b"generated")
    installer.install(tmp_path)
    assert not cache.exists()


def test_install_refuses_symlink_destination(tmp_path):
    target = tmp_path / "outside"
    target.mkdir()
    destination = tmp_path / "plugins" / "model-providers" / PROVIDER_NAME
    destination.parent.mkdir(parents=True)
    destination.symlink_to(target, target_is_directory=True)
    with pytest.raises(RuntimeError, match="unowned"):
        installer.install(tmp_path)


def test_install_preflight_preserves_owned_peer_when_other_target_is_unowned(tmp_path):
    installer.install(tmp_path)
    provider = tmp_path / "plugins" / "model-providers" / PROVIDER_NAME
    before = (provider / "__init__.py").read_bytes()
    general = tmp_path / "plugins" / PROVIDER_NAME
    (general / "__init__.py").write_text("user content\n")

    with pytest.raises(RuntimeError, match="unowned"):
        installer.install(tmp_path)

    assert (provider / "__init__.py").read_bytes() == before
    assert (general / "__init__.py").read_text() == "user content\n"


def test_install_refuses_extra_user_file(tmp_path):
    installer.install(tmp_path)
    destination = tmp_path / "plugins" / PROVIDER_NAME
    (destination / "notes.txt").write_text("keep me\n")
    with pytest.raises(RuntimeError, match="unowned"):
        installer.install(tmp_path)
    assert (destination / "notes.txt").read_text() == "keep me\n"


def test_uninstall_removes_only_exact_owned_content(tmp_path):
    installer.install(tmp_path)
    result = installer.uninstall(tmp_path)
    assert result["status"] == "removed"
    assert len(result["removed"]) == 2


def test_uninstall_refuses_modified_directory(tmp_path):
    installer.install(tmp_path)
    path = tmp_path / "plugins" / PROVIDER_NAME / "__init__.py"
    path.write_text("user content\n")
    result = installer.uninstall(tmp_path)
    assert result["status"] == "refused"
    assert str(path.parent) in result["refused"]
    assert path.exists()


def test_auto_enable_uses_noninteractive_permission_flag():
    calls = []

    class Result:
        returncode = 0

    assert installer._auto_enable_general_plugin(
        which=lambda _: "/usr/bin/hermes",
        run=lambda command, **kwargs: calls.append((command, kwargs)) or Result(),
    )
    assert "--no-allow-tool-override" in calls[0][0]
